version: "3.9"

services:
  zabbix-mariadb:
    image: mysql:8.0.32-debian
    container_name: zabbix-mariadb
    hostname: zabbix-mariadb
    restart: always
    environment:
      TZ: "Asia/Krasnoyarsk"
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: zabbix
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - zabbix
    volumes:
      - ${DATA}:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf:ro
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  zabbix-server:
    image: zabbix/zabbix-server-mysql:6.2.5-alpine
    container_name: zabbix-server
    hostname: zabbix-server
    restart: always
    environment:
      TZ: "Asia/Krasnoyarsk"
      DB_SERVER_HOST: zabbix-mariadb
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - zabbix
    depends_on:
      - zabbix-mariadb

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.2.5
    container_name: zabbix-web
    hostname: zabbix-web
    restart: always
    environment:
      TZ: "Asia/Krasnoyarsk"
      DB_SERVER_HOST: zabbix-mariadb
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: "Asia/Krasnoyarsk"
    ports:
      - 80:8080
      - 443:8443
    networks:
      - zabbix
    depends_on:
      - zabbix-mariadb
      - zabbix-server

networks:
  zabbix:
    driver: default